### ISSUE TITLE
[BUG] Can't create pool size larger that 3 and can't get over a threshold speed.

### ISSUE THREAD

**Issue by rushi3691** [iyear/tdl#249] opened 2023-07-24 21:39 UTC
**Describe the bug**
Whenever i give pool value greater than 3 like --pool 4 while downloading, it run for few seconds, then the program terminates itself. Also I've tried many ways to increase the speed. but its not getting above 3.5MBps (which is the highest I've recorded). But on telegram desktop i can get the maximum speed as of my wifi(which is about 9-10MBps). 
Since the pool value is 3 by default, i guess, it gets 1MBps per connection. In my opinion to get maxium throughput, the number of pool connection must also be higher.

**To Reproduce**
tdl dl -f result.json --pool 4

**Expected behavior**
I should be able to get as much speed as desktop client. 

I also want to contribute to this project. Let me know what I need to know and how can I help in any way.

**Comment by iyear** [comment] 2023-07-26 07:08
Excessively large thread pools or thread counts will force the connection to be closed by the Telegram server side. Download speed has always been a black box, especially when downloading across DCs is slow.

I don't know what the cause is at the moment.

**Comment by iyear** [comment] 2023-07-26 07:10
My guess is that the Telegram server treats the client's connection traits differently. That's why the official client tends to be faster across DCs. But I don't know exactly why.

**Comment by roskyz** [comment] 2023-08-03 03:40
Probably due to networking problem. No problems were found as regards direct connection.

- Try to setup the `--proxy` parameter to access the telegram gateway through the proxy.
- Start download tasks for a while, then manually restart the proxy server.
- *Problem occurred*. In addition, the download speed could drop randomly compared with direct connection.

FYI: https://github.com/gotd/td/issues/1030

**Comment by iyear** [comment] 2023-11-21 16:10
Please upgrade to [v0.13.0](https://github.com/iyear/tdl/releases/tag/v0.13.0) and feel free to reopen the issue if you have any questions.

**Closed by iyear** 2023-11-21 16:10 UTC
Labels: bug
