### ISSUE TITLE
[Bug] When use the "takeout" option, download will never start.

### ISSUE THREAD

**Issue by Lilacist** [iyear/tdl#646] opened 2024-06-13 16:19 UTC
### Describe the bug

When I use the "takeout" option,the download will never start. After the "takeout" option removed and keep the rest cli same,it works.
I turned on the debug option and saved the log,I will put it in Additional context.
So, what does the "takeout" switch mean? And why I stuck here?
If it is my fault, please help me resolve it,thank you very much!

### To Reproduce

1.run the program with "takeout" option.
2.download will never start.
![微信图片_20240614000738](https://github.com/iyear/tdl/assets/22196547/a76e0b16-3594-47c7-9d38-22c2cb0ac635)
3. Remove the "takeout" option and it will start download immediately.

### Expected behavior

It should start normally.

### Version

Version: 0.17.1
Commit: 7f4e543
Date: 2024-05-29T14:50:17Z

go1.21.10 windows/amd64

### Which OS are you running tdl on?

Windows

### Additional context

[https://github.com/Lilacist/logs/blob/main/takeout.log](https://github.com/Lilacist/logs/blob/main/takeout.log)

**Comment by papaj-na-wrotkach** [comment] 2024-06-19 17:18
#247 duplicate

**Comment by iyear** [comment] 2024-09-16 05:58
Duplicate of #247. Please track the fix progress in the original issue. I will try to fix the takeout issue soon.

**Closed by iyear** 2024-09-16 05:58 UTC
Labels: bug

**Comment by iyear** [comment] 2024-10-03 05:45
Please try v0.17.5

**Comment by Abu3safeer** [comment] 2024-10-05 19:07
it works but the same speed, it makes no effect
![image](https://github.com/user-attachments/assets/7e7815ff-2e73-4d52-882c-ecd5301a13ad)
