### ISSUE TITLE
[Bug]empty message content, skip send:

### ISSUE THREAD

**Issue by U75258** [iyear/tdl#761] opened 2024-10-27 15:28 UTC
### Describe the bug

The latest version cannot be forwarded. @i

### To Reproduce

empty message content, skip send:

### Expected behavior

empty message content, skip send:

### Version

lastnew

### Which OS are you running tdl on?

Linux

**Comment by the4anoni** [comment] 2024-10-28 06:06
Same issue for me, 0.17.5 works perfectly

**Comment by iyear** [comment] 2024-10-28 06:52
Can you provide a public link for me to reproduce it?

**Comment by kuhytitusdlz** [comment] 2024-10-28 12:19
the same issue (can't forward image or video) in private chat: forward not work, but download - work

**Comment by U75258** [comment] 2024-10-30 17:09
> Can you provide a public link for me to reproduce it?

https://t.me/tgcnx/6718964
please

**Comment by iyear** [comment] 2024-11-01 04:36
@U75258 I can't reproduce locally.

command: `tdl forward --from https://t.me/tgcnx/6718964 --to MY_CHAT --mode clone`

![image](https://github.com/user-attachments/assets/973fb86f-710a-4cd8-a53b-e80f6593d9f3)

**Comment by iyear** [comment] 2024-11-01 07:17
Sorry, v0.17.6 has a serious bug. If you are using v0.17.6, please upgrade to the latest version immediately.
v0.17.6 has been marked as deprecated, please do not use it anymore.

**Closed by iyear** 2024-11-01 07:17 UTC
Labels: bug
