### ISSUE TITLE
[Feat] Is it possible to compile a version of serv00?

### ISSUE THREAD

**Issue by huomqh** [iyear/tdl#697] opened 2024-08-09 16:34 UTC
### Proposal

编译SERV00版本的话，可以配合alist的加密功能，把telegram的小电影传到网盘里

### Background

把telegram的小电影传到网盘里

### Workarounds

把telegram的小电影传到网盘里

**Comment by iyear** [comment] 2024-09-17 07:49
It looks like `serv00` needs to use the FreeBSD binary file. The official release does not provide that version.

Duplicate of https://github.com/iyear/tdl/issues/389

**Closed by iyear** 2024-09-17 07:49 UTC
Labels: enhancement
